### ISSUE TITLE
Allow querying other sources apart form file and rdfjsSource

### ISSUE THREAD

**Issue by julianrojas87** [RubenVerborgh/LDflex-Comunica#16]
Is there reason to restrict the type of sources to be queried? I see [here](https://github.com/RubenVerborgh/LDflex-Comunica/blob/b34eb143d64669d0970a733d44a7f97bcd4746c0/src/ComunicaEngine.js#L96) that `file` and `rdfsSource` are the only allowed types.

I removed this restriction locally and it works well doing federated queries including `sparql` and `hypermedia` types. If needed I can pull request for this.

**Comment by rubensworks** [comment]
Now that source identification in comunica is improved, we can probably just remove the `type` tag on sources. (we still need them for `rdfjsSource` though).

**Comment by julianrojas87** [comment]
I did this and it worked fine explicitly defining the `type` of source or just giving it as a string:
```javascript
   return sources.map(src => ({
      value: src.value ? src.value : src,
      type: src.type ? src.type : undefined,
   }));
```
