### ISSUE TITLE
Subscribe to updates via websocket

### ISSUE THREAD

**Issue by RubenVerborgh** [RubenVerborgh/LDflex-Comunica#4]
As proposed in https://github.com/Inrupt-inc/solid-react-sdk/issues/3, we could subscribe to updates via web sockets.

We would not necessarily need to parse updates; a change triggering an "invalidate cache" could be enough.

**Comment by rubensworks** [comment]
Relevant cache invalidation issue in comunica: comunica/comunica#341

**Comment by RubenVerborgh** [comment]
Also see #10.
